Adds additional unit for degrees, with option to include it in csv
betaflight/blackbox-tools pull request #43
Opened 2021-05-02 00:23 UTC by dellch

Fixes #39 

Adds additional unit for degrees, _"deg"_, with option to include it in csv for roll/pitch/heading.  

This additional unit will not be included in the headers unless the (newly created) flag `--include-imu-degrees`

2021-05-02 00:25 UTC, dellch commented
This fixes #39 in a way that hopefully won't break any existing integrations, because it requires an additional CLI flag.  

Tried to follow standards - please let me know if there are any issues, or if the cli flag should be renamed.  

Also, been a _looong_ time since C, so excuse any glaring mistakes.

2021-05-02 00:27 UTC, dellch commented
Also, nobody would want the unit to be in radians, right?

2021-05-02 01:04 UTC, dellch commented on src/blackbox_decode.c
> +    bool haveRequiredFields = log->gpsFieldIndexes.GPS_coord[0] != -1 && log->gpsFieldIndexes.GPS_coord[1] != -1 && log->gpsFieldIndexes.GPS_altitude != -1;
these spacing changes were accidental, probably by my IDE - I'll work on reverting them

2021-05-02 01:07 UTC, dellch commented on src/blackbox_decode.c
> +    bool haveRequiredFields = log->gpsFieldIndexes.GPS_coord[0] != -1 && log->gpsFieldIndexes.GPS_coord[1] != -1 && log->gpsFieldIndexes.GPS_altitude != -1;
actually, it looks like the spacing is correct now - I think my IDE automatically converted all tabs to spaces.  Please let me know if I should fix this.  I didn't want to clutter the PR

2021-05-05 22:12 UTC, haslinghuis commented on src/blackbox_decode.c
> +        }else{
:space_invader: 
```suggestion
        } else {
```

2021-05-05 22:14 UTC, haslinghuis requested changes
Spacing seems ok now, thanks, one styling change left.

2021-05-06 03:20 UTC, dellch commented on src/blackbox_decode.c
> +        }else{
Thanks for catching that

2021-05-06 06:01 UTC, McGiverGim approved these changes
To me the code is ok. I don't know if it will be a very useful option, but is optional.

2021-05-06 10:53 UTC, haslinghuis approved these changes

2021-05-17 13:01 UTC, mikeller approved these changes

2021-05-17 13:06 UTC, mikeller commented
Manually tested the build - it's working.

2021-05-17 13:07 UTC, merged